### ISSUE TITLE
应用还是有点复杂

### ISSUE THREAD

**Issue by binvb** [zhujiaming/electron-wpc#2]
在Mainprocess注册了对应的token，各个窗口之间还是按照原来的方法通过on监听进行对应的操作就好。不知道这样如何，如果可以的话，我提个pr更新下

**Comment by binvb** [comment]
缺考虑，关闭

**Comment by zhujiaming** [comment]
谢谢提的意见。
双窗口间(renderer进程)消息通信中对renderer中的on进行了包装主要是为了方便将消息发送方的代理对象hander传入on的监听器中，方便在on中处理完毕业务后，直接通过handler回复消息给发送方，从而实现两个窗口相互间一次连接多次便捷通信。
可以参考多窗口间(renderer进程)广播通信的方式，这种在renderer中还是按照electron方法通过on监听。
